{
  "openapi": "3.0.3",
  "info": {
    "title": "Next Parking API",
    "description": "API description in Markdown.",
    "version": "1.1.0"
  },
  "servers": [
    {
      "url": "http://localhost:8181/api"
    },
    {
      "url": "http://35.219.32.97/api"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a list of users.",
        "description": "Will return all registered users available.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/users"
                  }
                },
                "examples": {
                  "success": {
                    "description": "Success get all users",
                    "value": [
                      {
                        "id_user": 1,
                        "full_name": "Anna Karenina Jusuf",
                        "phone_number": "1122336",
                        "email": "akarenina25@gmail.com",
                        "password": "$2b$12$6EWNxS4wXfPauPZs.m3KXuTS0XaPizAYNKh2ZcNHE/yx3bx6u4xC.",
                        "verification_pin": "$2b$12$6EWNxS4wXfPauPZs.m3KXuG1mS/LYM.MdsUJkzkEXZDL/nPAXfP2m",
                        "device_token": "ddd",
                        "balance": 0
                      },
                      {
                        "id_user": 2,
                        "full_name": "Sahir Syatha",
                        "phone_number": "087785255146",
                        "email": "sahirsyatha77@gmail.com",
                        "password": "$2b$12$yLuMtOLTvXoJA5BpHbgl5.hkqe9eRYjJyW1WU/VwEhcr91l8/1BdW",
                        "verification_pin": "$2b$12$yLuMtOLTvXoJA5BpHbgl5.6pZ1mU8ikABT19HW6Qkl0yOKf5mpZsO",
                        "device_token": "e_0IXVmqSwqVMhWBdVqabM:APA91bHfrUzS7E-ynPDftfYiQDRRPvrwYsqPUtJKiMB9jTOlDLlw-pQPNiVjkbacKdmFVo1OWRC6sVNlIdfZUTqt04vu3FNkmtxlIgkeaumlwjHrCxaN6-F9dn8xQe6IXcqJCnbBuyMA",
                        "balance": 0
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a user.",
        "description": "Will return a single user from database.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "To get the user by id.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id_user": {
                      "type": "string"
                    },
                    "full_name": {
                      "type": "string"
                    },
                    "phone_number": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    },
                    "verification_pin": {
                      "type": "string"
                    },
                    "device_token": {
                      "type": "string"
                    },
                    "balance": {
                      "type": "integer"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Success get one user",
                    "value": {
                      "id_user": 1,
                      "full_name": "Anna Karenina Jusuf",
                      "phone_number": "1122336",
                      "email": "akarenina25@gmail.com",
                      "password": "$2b$12$6EWNxS4wXfPauPZs.m3KXuTS0XaPizAYNKh2ZcNHE/yx3bx6u4xC.",
                      "verification_pin": "$2b$12$6EWNxS4wXfPauPZs.m3KXuG1mS/LYM.MdsUJkzkEXZDL/nPAXfP2m",
                      "device_token": "ddd",
                      "balance": 0
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete single user from database",
        "description": "Will delete a single user by id from paths",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "To get the user by id."
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "To get the user by id."
          },
          {
            "name": "full_name",
            "in": "query",
            "description": "To change user full name."
          },
          {
            "name": "phone_number",
            "in": "query",
            "description": "To change user phone number."
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Login user from query",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "device_token": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Nevindra": {
                  "description": "Example of login user",
                  "value": {
                    "email": "nevindraibnazhifi@gmail.com",
                    "password": "2fuckingco0l",
                    "device_token": 1234
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/users"
                },
                "examples": {
                  "success": {
                    "description": "Success get one user",
                    "value": {
                      "id_user": 4,
                      "full_name": "Nevindra Ibnazhifi",
                      "phone_number": "082213656160",
                      "email": "nevindraibnazhifi@gmail.com",
                      "password": "$2b$12$KX6hnoEMj.HlvrYtlNuLOORign5JmCFh3igaJlffLp3Of.Q0w8EQy",
                      "verification_pin": "$2b$12$KX6hnoEMj.HlvrYtlNuLOOlLrS.T9n1FmPJWFVMT8IDiLxJTPT7Ze",
                      "device_token": "1234",
                      "balance": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/registration": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "full_name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "phone_number": {
                    "type": "string"
                  },
                  "verification_pin": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "CREATED"
          }
        }
      }
    },
    "/verification-mail": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "To be Added",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/forgot-password": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "To be Added",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/vehicles": {
      "get": {
        "tags": [
          "Vehicles"
        ],
        "summary": "Return a list of all vehicles",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/vehicles"
                }
              }
            }
          }
        }
      }
    },
    "/vehicles/{id_user}": {
      "get": {
        "tags": [
          "Vehicles"
        ],
        "summary": "Return a list of vehicles for specific user",
        "parameters": [
          {
            "name": "id_user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/vehicles"
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "summary": "Delete a vehicles for spesific user",
        "tags": [
          "Vehicles"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/vehicles"
                }
              }
            }
          }
        }
      }
    },
    "/vehicles/{id_user}/{id_vehicle}": {
      "get": {
        "tags": [
          "Vehicles"
        ],
        "summary": "Return a list of vehicles for specific user and vehicle",
        "parameters": [
          {
            "name": "id_user",
            "in": "path",
            "required": true
          },
          {
            "name": "id_vehicle",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/register-vehicles": {
      "post": {
        "tags": [
          "Vehicles"
        ],
        "summary": "Register new vehicle for certain user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id_user": {
                    "type": "integer"
                  },
                  "plate_number": {
                    "type": "string"
                  },
                  "car_type": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "CREATED"
          }
        }
      }
    },
    "/transactions/{id}": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "Get all transactions for a single user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of user",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/topup/:id": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "Get all top up history from a user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/payment": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "To pay active transactions",
        "parameters": [
          {
            "name": "id_user",
            "in": "query",
            "required": true
          },
          {
            "name": "verification_token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/confirm-pin": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "To confirm identity of user",
        "parameters": [
          {
            "name": "id_user",
            "in": "query",
            "required": true
          },
          {
            "name": "verification_pin",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Wrong Password"
          }
        }
      }
    },
    "/topup": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "Top up user saldo",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id_user": {
                    "type": "integer"
                  },
                  "amount": {
                    "type": "integer"
                  },
                  "payment_method": {
                    "type": "string"
                  },
                  "verification_pin": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "users": {
        "type": "object",
        "properties": {
          "id_user": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          },
          "phone_number": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "verification_pin": {
            "type": "string"
          },
          "device_token": {
            "type": "string"
          },
          "balance": {
            "type": "integer"
          }
        }
      },
      "vehicles": {
        "type": "object",
        "properties": {
          "id_user": {
            "type": "integer"
          },
          "id_vehicle": {
            "type": "integer"
          },
          "plate_number": {
            "type": "string"
          },
          "car_type": {
            "type": "string"
          },
          "last_parking": {
            "type": "string"
          },
          "isVerified": {
            "type": "boolean"
          }
        }
      }
    }
  }
}